### ISSUE TITLE
Consider using PropTypes

### ISSUE THREAD

**Issue by gomorizsolt** [c-hive/guides#33] opened 2019-12-22 13:30 UTC
https://github.com/facebook/prop-types

**Comment by gomorizsolt** [comment] 2019-12-26 18:51
Stumbled upon the fact that the package *does not* warn in case of missing props/misaligned props unless the project runs in the browser. Found this "counter-intuitive". I think it'd make sense to receive errors/warnings without running the app and constantly checking the logs. Perhaps it's only possible with static type-checking, see https://reactjs.org/docs/static-type-checking.html.

Apart from this, incorporated `prop-types` into https://github.com/gomorizsolt/react-boilerplate to be able to play around with this a bit.

**Comment by thisismydesign** [comment] 2019-12-27 17:26
AFAIK it only runs in development mode, wasn't aware of the browser limitation, do you have a source for this?

**Comment by gomorizsolt** [comment] 2019-12-30 08:19
> AFAIK it only runs in development mode, wasn't aware of the browser limitation,

Perhaps I wasn't so precise. It's not limited to browsers. My expectation was that prop-types would throw error messages in case of missing/misaligned props while editing the code but it warns in the browser's console instead. That's why it's required to have a running instance of the app in the background.

> AFAIK it only runs in development mode

I'm not sure. Interestingly though, the owners do *not* suggest installing prop-types as a dev-dependency => `npm install --save prop-types`. I guess therefore it's definitely possible to receive the errors/warnings in production mode.

**Comment by gomorizsolt** [comment] 2019-12-30 08:22
We can make sure whether it's possible to build the app if there's an error regarding wrong prop-types.

Does it make sense?

**Comment by thisismydesign** [comment] 2019-12-30 12:05
`prop-types` only provides warning in dev mode on the console (whichever console that may be). This is by design: 

> When an invalid value is provided for a prop, a warning will be shown in the JavaScript console. For performance reasons, propTypes is only checked in development mode.

https://reactjs.org/docs/typechecking-with-proptypes.html

> My expectation was that prop-types would throw error messages in case of missing/misaligned props while editing the code

You'd need compilation and static types to do that.

**Comment by thisismydesign** [comment] 2019-12-30 12:06
The best you can do in enable an eslint rule for missing prop type definitions, you can only check prop types during execution.

**Comment by gomorizsolt** [comment] 2019-12-30 12:11
> The best you can do in enable an eslint rule for missing prop type definitions, you can only check prop types during execution.

Yea, that rule was disabled. Thanks for the help and clarifications.

**Comment by thisismydesign** [comment] 2020-06-26 01:14
I'd close this, I think propTypes make sense unless there's a better alternative. By default our ESLint config will warn to use it.

I found this comparison of alternatives interesting: https://hackernoon.com/why-i-no-longer-use-typescript-with-react-and-why-you-shouldnt-either-e744d27452b4

Next I'd take a look at Flow and how well it's supported (is there good tooling, and whether it interferes with existing tooling).

**Closed by thisismydesign** 2020-06-26 01:14 UTC
